### ISSUE TITLE
l error: Undefined class constant

### ISSUE THREAD

**Issue by robozeri** [ItalianDevs4PM/Yuriko-MP#1]
Undefined class constant 'RABBIT_STEW' in /home/mcpe/Yuriko-MP/src/pocketmine/item/Item.php on line 621

**Comment by AryToNeX** [comment]
@robozeri Ancora non abbiamo finito il progetto. Torna fra qualche mese.

**Comment by robozeri** [comment]
Ho segnalato l'errore se uno non lo può testare che senso ha..
Il giorno 03/gen/2016 21:04, "Anthony Calabretta" <notifications@github.com>
ha scritto:

**Comment by AryToNeX** [comment]
@robozeri Ci sono cose che stiamo sistemando, stai calmo

**Comment by xionbig** [comment]
@AryToNeX Test2

**Comment by robozeri** [comment]
Sono calmo pensavo che vi fosse d'aiuto

**Comment by AryToNeX** [comment]
@robozeri Nah Salvo, dovresti conoscermi, io testo tutto e so tutto ;P

**Comment by robozeri** [comment]
Va bene volevo solo vedere un po il progetto visto che mi piace ma okey.
Il giorno 03/gen/2016 21:15, "Anthony Calabretta" <notifications@github.com>
ha scritto:
